### PR TITLE
Updating index to include some new links

### PR DESCRIPTION
**Pull request by joicemjoseph**
ref #2 
time-taken: 10 mins
removed ga
added up some new links
gave a new href to learn more. ( https://www.change.org/p/rsprasad-trai-don-t-allow-differential-pricing-of-services-let-consumers-choose-how-they-want-to-use-internet-netneutrality )

### CODE REVIEW

**Comment by jace** [comment]
Since we need analytics for this site, we cannot remove GA until an alternative is place.

**Comment by joicemjoseph** [comment]
@jace what about w3ccounter

**Comment by joicemjoseph** [comment]
guys, here is something more links I have found. this link have translation in many language including Malayalam.
https://aravindet.svbtle.com/appu-and-the-bus-operators
this simplifies how the structure of this corporates are getting richer and richer by making foolish tales like what is happening in the petroleum field.

**Comment by karthikb351** [comment]
@aravindet made this site too. :)

**Comment by joicemjoseph** [comment]
Haha...
I didnt checked them out yet.. yea... sounds great pal.. good work anyway..
So you wanna read the malayalam translation ??
here is the link :- https://diasp.eu/posts/2991875

**Comment by joicemjoseph** [comment]
@aravindet can you just  change ga to something else please ??

**Comment by jace** [comment]
Our primary goal right now is to direct people to make submissions to TRAI, so we're working on that. We're not convinced GA is a problem. Many sites including this very GitHub page use GA.

**Comment by joicemjoseph** [comment]
yes.
We have something to do. but considering these tiny bits might be valuable.

**Comment by aravindet** [comment]
@joicemjoseph awesome! :-)

like @jace said. one of the things we have to do right now is to be entirely focused on sending responses to TRAI. Working as a team means that sometimes people have different opinions on peripheral things while having a common agenda. Let’s focus on the tasks that we have consensus on.

p.s. GA gives vastly better analytics (the raw data is the same, but GA gives more options off the shelf to segment, do cohort analysis etc.), and a lot of us have years of experience using the GA interface to get insights out of it. (It’s surprisingly complex to learn, and the terminology is not always transferable to a new tool).

p.p.s. We also use Google Fonts. And a public Google Drive. Just saying.

**Comment by jace** [comment]
Google, Facebook and Twitter are all violators of network neutrality in India. If we boycott them as a result, we have no way to reach anyone with this campaign. Instead we have to practice Internet judo, using their own strength against them. We have to maximise our reach using Google, Facebook and Twitter to tell everyone why they have to participate in this campaign.

**Comment by joicemjoseph** [comment]
@aravindet ,  @jace OK fine.   focusing on the plans, 
there is something we can do here.
Localization is the best thing to involve other non-techie  people to involve in this campaign.
here in Kerala some amazing guys like praveen and some other team done translating @aravindet 's story to malayalam and sharing to many social networks. so make people involve in this.

PS: Appu's tea stall is busy by lot of NN activists. [http://www.thehindubusinessline.com/opinion/columns/appus-price-for-net-neutrality/article7081725.ece]

**Comment by jace** [comment]
That's a good idea. I think TRAI will take submissions only in English, but the information page itself could be translated. Maybe we can do `/ml` `/hi` etc URLs for the translated versions of the pages.

**Comment by joicemjoseph** [comment]
so lets move this discussion to IRC. I think that is gonna be better

**Comment by joicemjoseph** [comment]
please join #nnindia on freenode

**Pull request closed without merging**
