### PR TITLE
Added malaayalam translation to the files and related files

### PR DESCRIPTION
**Pull request by joicemjoseph**

### CODE REVIEW

**Comment by karthikb351** [comment]
Great!
Small change though, you need update this PR so it's against the `/src` folder. Not `/dist`.

`/dist` is the compiled/minified build of the `/src` folder

**Comment by joicemjoseph** [comment]
hope I done so..
but forget to change the pic.. in fact that might not cause you trouble.

**Comment by aravindet** [comment]
Folks, there are a few typos. E.g. the heading,
  ഇന്റര്നെറ്റ് സ്വാതന്ത്രത്തിനു വേണ്ടി... should be
  ഇന്റർനെറ്റ്‌ സ്വാതന്ദ്ര്യതിനു വേണ്ടി

**Comment by karthikb351** [comment]
Deployed. Live at http://www.netneutrality.in/index-ml.html

@aravindet and @joicemjoseph please send fixes, if any.

**Comment by joicemjoseph** [comment]
@aravindet can you do that ?? I made a bare translation of it. In fact I just meant, barely just internet, neutral internet is what we want.

**Pull request merged**
